[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pytchat-ng"
version = "0.5.8"
description = "a python library for fetching youtube live chat. (next generation)"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.7"
authors = [
    {name = "revertical", email = "screenkidgreen7@gmail.com"},
]
keywords = ["youtube", "livechat", "asyncio"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
dependencies = [
    "httpx[http2]",
]

[project.optional-dependencies]
test = [
    "pytest-mock",
    "pytest-httpx",
]

[project.urls]
Homepage = "https://github.com/revertical/pytchat-ng"

[tool.setuptools.packages.find]
exclude = ["tests*", "testrun*"]
